SECRET_KEY = 'enter key here'
SQLALCHEMY_DATABASE_URI= "mysql+pymysql://"
SQLALCHEMY_TRACK_MODIFICATIONS = False
ENV = 'dev'
DEBUG = True
DEBUG_TB_INTERCEPT_REDIRECTS = False
DEBUG_TB_ENABLED = True
CACHE_TYPE = 'null'
CACHE_NO_NULL_WARNING = True
BOOTSTRAP_SERVE_LOCAL = True
USERS_PER_PAGE = 3

